{{- if .Values.ingress.enabled -}}
{{- $ingressPath := .Values.pathBase -}}
{{- $serviceName := .Values.app.svc.webstatus -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
#  annotations:
#    nginx.ingress.kubernetes.io/server-snippet: |
#      location /webstatus {
#        use-forwarded-headers "true";
#      }
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if and .Values.inf.tls.enabled .Values.inf.tls.issuer }}
    cert-manager.io/issuer: {{ .Values.inf.tls.issuer }} 
{{- end }}
{{- if .Values.inf.mesh.enabled }} 
{{- with .Values.ingress.mesh.annotations }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - http:
      paths:
#        - path: {{ $ingressPath }}(/|$)(.*)
        - path: {{ $ingressPath }}
          pathType: Prefix
          backend:
            service:
              name: {{ $serviceName }}
              port:
                name: http
{{- end }}
