# Default values for fluent-bit.

image:
  repository: fluent/fluentd-kubernetes-daemonset
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

rbac:
  create: true

# Configure podsecuritypolicy
# Ref: https://kubernetes.io/docs/concepts/policy/pod-security-policy/
podSecurityPolicy:
  enabled: true
  annotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 24231
  annotations:
    {}
    # prometheus.io/path: "/metrics"
    # prometheus.io/port: "24231"
    # prometheus.io/scrape: "true"

resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {sidecar.istio.io/inject: "false"}

priorityClassName: ""

env:
  - name: FLUENT_ELASTICSEARCH_HOST
    value: "emarket-coordinating-only"
  - name: FLUENT_ELASTICSEARCH_PORT
    value: "9200"
  - name: FLUENTD_SYSTEMD_CONF
    value: 'disable'

envFrom: []

extraVolumes: []

extraVolumeMounts: []

# DaemonSet or Deployment
kind: DaemonSet

# Only applicable for Deployment
replicaCount: 1
