apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluentd.fullname" . }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # - port: 24224
    #   targetPort: forward
    #   protocol: TCP
    #   name: forward
    - port: 24231
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "fluentd.selectorLabels" . | nindent 4 }}
