apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: emarket-identity-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emarket-identity-api
  minReplicas: {{ .Values.global.hpa.minReplicas }}
  maxReplicas: {{ .Values.global.hpa.maxReplicas }}
  metrics:
  - resource:
      name: memory
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  - resource:
      name: cpu
      target:
        averageUtilization: 15
        type: Utilization
    type: Resource
