apiVersion: v1
kind: Service
metadata:
  labels:
    app: marketingapi
  name: marketingapi
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: marketingapi
  type: ClusterIP
