{{- $name := include "webstatus.fullname" . -}}
{{- $sqlsrv := include "sql-name" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webstatus.name" . }}
    chart: {{ template "webstatus.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  cfgmap__EMARKET_HTTP_PORT: "{{ .Values.service.port }}"
  cfgmap__EMARKET_GRPC_PORT: "{{ .Values.service.grpcPort }}"
#  cfgmap__ConnectionString: Server={{ $sqlsrv }};Initial Catalog={{ .Values.global.sql.identity.db }};User Id={{ .Values.global.sql.common.user }};Password={{ .Values.global.sql.common.pwd }};
#  cfgmap__EMARKET_SQL_DATA_URL: "jdbc:mariadb://{{ $sqlsrv }}:{{ .Values.global.sql.port }}/{{ .Values.global.sql.identity.db }}"
#  cfgmap__EMARKET_SQL_DATA_USER: "{{ .Values.global.sql.common.user }}"
#  cfgmap__EMARKET_SQL_DATA_PASSWORD: "{{ .Values.global.sql.common.pwd }}"
  cfgmap__EMARKET_EVENTBUS_HOST: {{ .Values.global.eventbus.svc }}
  cfgmap__EMARKET_EVENTBUS_PORT: "{{ .Values.global.eventbus.port }}"
  cfgmap__EMARKET_EVENTBUS_USERNAME: "{{ .Values.global.eventbus.username }}"
  cfgmap__EMARKET_EVENTBUS_PASSWORD: "{{ .Values.global.eventbus.password }}"
  cfgmap__EMARKET_EVENTBUS_SSL: "{{ .Values.global.eventbus.ssl.enabled }}"
  cfgmap_EMARKET_TRACE_INTERVAL: "{{ .Values.global.tracing.traceinterval }}"
  cfgmap__EMARKET_PUBLIC_URL: "{{ .Values.service.publicurl }}"
#  cfgmap__EnableLoadTest: "{{ .Values.global.misc.useLoadTest }}"
#  urls__IdentityUrl: http://{{ .Values.global.svc.identity }}
#  all__EventBusConnection: {{ .Values.global.eventbus.svc }}
#  all__InstrumentationKey: "{{ .Values.global.appinsights.key }}"
#  all__UseAzureServiceBus: "{{ .Values.global.eventbus.useAzure }}"
