replicaCount: 1
clusterName: emarket-cluster
pathBase: /webhooks-node

image:
  repository: emarket/webhooks-node
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

dependsOn:
  - nosql-data

ingress:
  enabled: true
  annotations: {}
  hosts:
    - chart-example.local
  tls: []


resources:
  limits:
    cpu: 300m
    memory: 700Mi
  requests:
     cpu: 200m
     memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}

# env defines the environment variables that will be declared in the pod
env:
  urls:
  # configmap declares variables which value is taken from the config map defined in template configmap.yaml (name is name of var and key the key in configmap).
  configmap:

    - name: EMARKET_NOSQL_DATA_URL
      key: webhooksnode__EMARKET_NOSQL_DATA_URL
    - name: Database
      key: webhooksnode__Database

#    - name: ConnectionString
#      key: cfgmap__ConnectionString
#    - name: EMARKET_SQL_DATA_URL
#      key: cfgmap__EMARKET_SQL_DATA_URL
#    - name: EMARKET_SQL_DATA_USER
#      key: cfgmap__EMARKET_SQL_DATA_USER
#    - name: EMARKET_SQL_DATA_PASSWORD
#      key: cfgmap__EMARKET_SQL_DATA_PASSWORD
#    - name: EMARKET_KEYSTORE_HOST
#      key: cfgmap__EMARKET_KEYSTORE_HOST
#    - name: EMARKET_EVENTBUS_HOST
#      key: cfgmap__EMARKET_EVENTBUS_HOST
#    - name: EMARKET_AUTH_SERVICE_HOST
#      key: cfgmap__EMARKET_AUTH_SERVICE_HOST
#    - name: EMARKET_AUTH_SERVICE_PORT
#      key: cfgmap__EMARKET_AUTH_SERVICE_PORT
#    - name: EMARKET_WEBSTATUS_SERVICE_HOST
#      key: cfgmap__EMARKET_WEBSTATUS_SERVICE_HOST
##    - name: ApplicationInsights__InstrumentationKey
##      key: all__InstrumentationKey
##    - name: EventBusConnection
#      key: all__EventBusConnection
#    - name: AzureServiceBusEnabled
#      key: all__UseAzureServiceBus
#    - name: UseLoadTest
#      key: cfgmap__EnableLoadTest
#    - name: IdentityUrl
#      key: urls__IdentityUrl
#    - name: EMARKET_HTTP_PORT
#      key: cfgmap__EMARKET_HTTP_PORT
#    - name: EMARKET_GRPC_PORT
#      key: cfgmap__EMARKET_GRPC_PORT
#      # values define environment variables with a fixed value (no configmap involved) (name is name of var, and value is its value)
  values:
#    - name: ASPNETCORE_ENVIRONMENT
#      value: Development
    - name: OrchestratorType
      value: 'K8S'
#    - name: PORT
#      value: 80
#    - name: GRPC_PORT
#      value: "81"      
probes:
  liveness:
    path: api/webhook-received
    timeoutSeconds: 5
    initialDelaySeconds: 60
    periodSeconds: 15
    port: 5000
  readiness:
    path: api/webhook-received
    timeoutSeconds: 5
    initialDelaySeconds: 60
    periodSeconds: 60
    port: 5000
