apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apigwws-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /webshoppingapigw/catalog-api/
    - uri:
        prefix: /webshoppingapigw/catalog-api
    rewrite:
        uri: /catalog-api/
    route:
    - destination:
        host: catalog-api
        port:
          number: 8080

  - match:
    - uri:
        prefix: /webshoppingapigw/c/
    rewrite:
        uri: /catalog-api/
    route:
    - destination:
        host: catalog-api
        port:
          number: 8080

  - match:
    - uri:
        prefix: /webshoppingapigw/ordering-api/
    - uri:
        prefix: /webshoppingapigw/ordering-api
    rewrite:
        uri: /ordering-api/
    route:
    - destination:
        host: ordering-api
        port:
          number: 8080

  - match:
    - uri:
        prefix: /webshoppingapigw/o/
    rewrite:
        uri: /ordering-api/
    route:
    - destination:
        host: ordering-api
        port:
          number: 8080

  - match:
    - uri:
        prefix: /webshoppingapigw/basket-api/
    - uri:
        prefix: /webshoppingapigw/basket-api
    rewrite:
        uri: /basket-api/
    route:
    - destination:
        host: basket-api
        port:
          number: 8080

  - match:
    - uri:
        prefix: /webshoppingapigw/b/
    rewrite:
        uri: /basket-api/
    route:
    - destination:
        host: basket-api
        port:
          number: 8080


  - match:
    - uri:
        prefix: /webshoppingapigw/image-api/
    - uri:
        prefix: /webshoppingapigw/image-api
    rewrite:
        uri: /image-api/
    route:
    - destination:
        host: image-api
        port:
          number: 8080

  - match:
    - uri:
        prefix: /webshoppingapigw/i/
    rewrite:
        uri: /image-api/
    route:
    - destination:
        host: image-api
        port:
          number: 8080


  - match:
    - uri:
        prefix: /webshoppingapigw/hub/notificationshub/
    - uri:
        prefix: /webshoppingapigw/hub/notificationshub
    rewrite:
        uri: /notificationshub/
    route:
    - destination:
        host: notification
        port:
          number: 8080
          
  - match:
    - uri:
        prefix: /webshoppingapigw/
    - uri:
        prefix: /webshoppingapigw
    rewrite:
        uri: /web-agg/
    route:
    - destination:
        host: webshoppingagg
        port:
          number: 8080
