apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apigwmm-vs
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /mobilemarketingapigw/marketing-api/
    - uri:
        prefix: /mobilemarketingapigw/marketing-api
    rewrite:
        uri: /marketing-api/
    route:
    - destination:
        host: marketing-api
        port:
          number: 5000

  - match:
    - uri:
        prefix: /moblemarketingapigw/m/
    rewrite:
        uri: /marketing-api/
    route:
    - destination:
        host: marketing-api
        port:
          number: 5000

  - match:
    - uri:
        prefix: /mobilemarketingapigw/locations-api/
    - uri:
        prefix: /mobilemarketingapigw/locations-api
    rewrite:
        uri: /locations-api/
    route:
    - destination:
        host: locations-api
        port:
          number: 5000

  - match:
    - uri:
        prefix: /mobilemarketingapigw/l/
    rewrite:
        uri: /locations-api/
    route:
    - destination:
        host: locations-api
        port:
          number: 5000

