apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: catalogapi-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /catalog-api
    - uri:
        prefix: /catalog-api/*
    - uri:
        prefix: /catalog-api/swagger-ui
    - uri:
        prefix: /catalog-api/swagger-ui/*
    route:
    - destination:
        host: catalog-api
        port:
          number: 8080
  http:
  - match:
    - uri:
        regex: /catalog-api
    route:
    - destination:
        host: catalog-api
        port:
          number: 8080

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: catalogapi-dr
  namespace: default
spec:
  host: catalog-api
  trafficPolicy:
    tls:
      mode: DISABLE

---

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: catalog-authz
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - to:
      - operation:
          methods: ["GET"]
          paths: ["/webshoppingapigw/c/api/v1/catalog/*","/webshoppingapigw/catalog-api/api/v1/catalog/*"]
