apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echoserver-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /echo
    - uri:
        prefix: /echo
    route:
    - destination:
        host: echoserver
        port:
          number: 80
    corsPolicy:
      allowOrigins:
      - regex:  ("*")
      allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - OPTIONS
      allowCredentials: true
      allowHeaders:
      - content-type
      - authorization
      - x-jwt-payload
      - cache-control
      - content-transfer-encoding
      - keep-alive
      maxAge: "24h"
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: echoserver-dr
  namespace: default
spec:
  host: echoserver
  trafficPolicy:
    tls:
      mode: DISABLE
---
      
