apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: imageapi-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /image-api
    - uri:
        prefix: /image-api/*
    - uri:
        prefix: /image-api/swagger-ui
    - uri:
        prefix: /imae-api/swagger-ui/*
    route:
    - destination:
        host: image-api
        port:
          number: 8080
  http:
  - match:
    - uri:
        regex: /image-api
    route:
    - destination:
        host: image-api
        port:
          number: 8080

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: imageapi-dr
  namespace: default
spec:
  host: image-api
  trafficPolicy:
    tls:
      mode: DISABLE

---

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: image-authz
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - to:
      - operation:
          methods: ["GET","POST","DELETE"]
          paths: ["/webshoppingapigw/i/*","/webshoppingapigw/image-api/*"]
      when:
      - key: request.auth.claims[iss]
        values: ["*"]   
