apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /jaeger
    - uri:
        prefix: /jaeger
    - uri:
        prefix: /js
    route:
    - destination:
        host: emarket-jaeger-query.default.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        regex: /jaeger
    route:
    - destination:
        host: emarket-jaeger-query.default.svc.cluster.local
        port:
          number: 80

  - match:
    - uri:
        regex: /js
    route:
    - destination:
        host: emarket-jaeger-query.default.svc.cluster.local
        port:
          number: 80

  - match:
    - uri:
        regex: /static
    route:
    - destination:
        host: emarket-jaeger-query.default.svc.cluster.local
        port:
          number: 80

  - match:
    - uri:
        regex: /static/css/*
    route:
    - destination:
        host: emarket-jaeger-query.default.svc.cluster.local
        port:
          number: 80
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: jaeger
  namespace: default
spec:
  host: emarket-jaeger-query.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
      
      
---     



