apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /identity/connect/auth
    - uri:
        prefix: /identity/connect
    route:
    - destination:
        host: keycloak-http.default.svc.cluster.local
        port:
          number: 8443
  - match:
    - uri:
        regex: /identity/connect
    route:
    - destination:
        host: keycloak-http.default.svc.cluster.local
        port:
          number: 8443

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: keycloak
  namespace: default
spec:
  host: keycloak-http.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      
--- 
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: keycloak-authz
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - to:
      - operation:
          methods: ["GET","POST","OPTIONS","PUT"]
          paths: ["/identity/connect/auth/*", "/identity/connect/*"]


