apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kibana
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        prefix: /kibana
    route:
    - destination:
        host: emarket-kibana
        port:
          number: 5601
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kibana
  namespace: default
spec:
  host: emarket-kibana
  trafficPolicy:
    tls:
      mode: DISABLE

---



