apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: marketingapi-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /marketing-api
    - uri:
        prefix: /marketing-api
    - uri:
        prefix: /marketing-api/
    - uri:
        prefix: /marketing-api/
    route:
    - destination:
        host: marketing-api
        port:
          number: 5000

  - match:
    - uri:
        regex: /marketing-api
    route:
    - destination:
        host: marketing-api
        port:
          number: 5000
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: marketingapi-dr
  namespace: default
spec:
  host: marketing-api
  trafficPolicy:
    tls:
      mode: DISABLE
      

---
   
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: marketing-authz
  namespace: istio-system
spec:
  action: ALLOW
  rules:
    - to:
      - operation:
          methods: ["GET"]
          paths: ["/webmarketingapigw/marketing-api/*","/mobilemarketingapigw/marketing-api/*","/webmarketingapigw/m/*"]
      when:
      - key: request.auth.claims[iss]
        values: ["*"]



