apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: minio
  namespace: default
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        regex: .*/emarket*.*
    route:
    - destination:
        host: emarket-minio
        port:
          number: 9000
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: minio
  namespace: default
spec:
  host: emarket-minio
  trafficPolicy:
    tls:
      mode: DISABLE

---
