apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mobileshopiingagg-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /mobile-agg
    - uri:
        prefix: /mobile-agg
    route:
    - destination:
        host: mobileshoppingagg
        port:
          number: 8080

  - match:
    - uri:
        regex: /mobile-agg
    route:
    - destination:
        host: mobileshoppingagg
        port:
          number: 8080
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mobileshoppingagg-dr
  namespace: default
spec:
  host: mobileshoppingagg
  trafficPolicy:
    tls:
      mode: DISABLE

