apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webstatus-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /webstatus
    - uri:
        prefix: /webstatus
    - uri:
        prefix: /webstatus/login
    route:
    - destination:
        host: webstatus
        port:
          number: 8080
  - match:
    - uri:
        regex: /webstatus/*
    route:
    - destination:
        host: webstatus
        port:
          number: 8080


---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: webstatus-dr
  namespace: default
spec:
  host: webstatus.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE

---
