apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: webshopiingagg-vs
spec:
  hosts:
  - "*"
  gateways:
  - ingress-gateway
  http:
  - match:
    - uri:
        exact: /web-agg
    - uri:
        prefix: /web-agg
    route:
    - destination:
        host: webshoppingagg
        port:
          number: 8080

  - match:
    - uri:
        regex: /web-agg
    route:
    - destination:
        host: webshoppingagg
        port:
          number: 8080
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: webshoppingagg-dr
  namespace: default
spec:
  host: webshoppingagg
  trafficPolicy:
    tls:
      mode: DISABLE

