{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  elasticsearch.yml: |- {{- toYaml .Values.config | nindent 4 }}
{{- end }}
