{{- $name := include "webspa.fullname" . -}}
{{- $identity := include "url-of" (list .Values.global.ingress.entries.identity .) -}}
{{- $webshoppingapigw := include "url-of" (list .Values.global.ingress.entries.webshoppingapigw .) -}}
{{- $webmarketingapigw := include "url-of" (list .Values.global.ingress.entries.webmarketingapigw .) -}}
{{- $spa := include "url-of" (list .Values.global.ingress.entries.spa .) -}}
{{- $mongo := include "mongo-name" . -}}
{{- $protocol := include "protocol" . -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ template "webspa.name" . }}
    chart: {{ template "webspa.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  all__InstrumentationKey: "{{ .Values.global.appinsights.key }}"
  all_EnableLoadTest: "{{ .Values.global.misc.useLoadTest }}"
  internalurls__apigwws: http://{{ .Values.global.svc.webshoppingapigw }}
  internalurls__identity__hc: http://{{ .Values.global.svc.identity }}/hc
  urls__apigwws: {{ $protocol }}://{{ $webshoppingapigw }}
  urls__spa: {{ $protocol }}://{{ $spa }}
  urls__IdentityUrl: {{ $protocol }}://{{ $identity }}
  urls__apigwwm: {{ $protocol }}://{{ $webmarketingapigw }}

#  webspa__keystore: {{ .Values.global.redis.standalone.svc }}
