apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
        - args:
            - --provider=oidc
            - --provider-display-name="Keycloak"
            - --email-domain=*
            - --pass-access-token=true
            - --pass-authorization-header=true
            - --set-authorization-header=true
            - --oidc-issuer-url=http://keycloak-http.default.svc.cluster.local/identity/connect/auth/realms/emarket-admin
            - --login-url=https://{{ .Values.global.app.url.default }}/identity/connect/auth/realms/emarket-admin/protocol/openid-connect/auth
            - --redeem-url=http://keycloak-http.default.svc.cluster.local/identity/connect/auth/realms/emarket-admin/protocol/openid-connect/token
            - --validate-url=https://{{ .Values.global.app.url.default }}/identity/connect/auth/realms/emarket-admin/protocol/openid-connect/userinfo
            - --http-address=0.0.0.0:4180
            - --cookie-expire=0h5m0s
            - --whitelist-domain={{ .Values.global.app.url.domain }}
            - --cookie-domain={{ .Values.global.app.url.domain }}
            - --standard-logging=true
            - --auth-logging=true
            - --request-logging=true
            - --skip-provider-button=true
            - --upstream=static://
            - --session-store-type=cookie
            - --insecure-oidc-allow-unverified-email=true
            - --cookie-secure=false
            - --skip-oidc-discovery=true
            - --insecure-oidc-skip-issuer-verification=true
            - --errors-to-info-log=true
            - --oidc-jwks-url=http://keycloak-http.default.svc.cluster.local/identity/connect/auth/realms/emarket-admin/protocol/openid-connect/certs

          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: sso
            - name: OAUTH2_PROXY_CLIENT_SECRET
              value: d0d20415-371c-4bee-852e-25f1bd3405f5
            - name: OAUTH2_PROXY_COOKIE_SECRET
              value: WWdxL0ZHNElzL3VQOFVON3YzKzFEQT09
            - name: OAUTH2_PROXY_COOKIE_DOMAIN
              value: {{ .Values.global.app.url.domain }}
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
          imagePullPolicy: IfNotPresent
          name: oauth2-proxy
          ports:
            - containerPort: 4180
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauthproxy-service
  namespace: default
spec:
  ports:
    - name: http
      port: 4180
      protocol: TCP
      targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
