apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: echo-oauth-proxy
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: CUSTOM
  provider:
    name: "oauth2-proxy"
  rules:
    - to:
      - operation:
          paths: [
            "/echo"
          ]

